### ISSUE TITLE
Same output when used with pipes as terraform, no download message

### ISSUE THREAD

**Issue by cbuschka** [cbuschka/tfvm#23]
* [ ] This is a bug report
* [x] This is a feature request

### Expected behavior

When tfvm output is piped it should behave exactly as terraform is run directly. I.e. no downloading info.

### Actual behavior

Tfvm prints a downloading message. This behaviours differs from a locally installed terraform.

**Comment by halostatue** [comment]
I definitely discovered this to be an issue when a new version of Terraform was downloaded during an automatically started `terraform fmt` run.

**Comment by cbuschka** [comment]
Fixed with commit eb08183, will be part of release 0.19.0.
