### ISSUE TITLE
Native darwin-arm64 build with extended download support

### ISSUE THREAD

**Issue by halostatue** [cbuschka/tfvm#25]
* [x] This is a feature request

This is in response to a [question](https://github.com/cbuschka/tfvm/pull/24#issuecomment-918832027) asked on #24 as well as a detailed request for a solution. The macOS on Apple Silicon issue is that, until terraform 1.0.2, there was no `arm64_darwin` build and as far as I know, there’s no build of `tfvm` for `arm64_darwin`. This mostly isn’t a problem with Rosetta 2 (emphasis on _mostly_; I get a _lot_ of weird network timeouts that I don’t think I’d get with native builds or running natively on `amd64_darwin`).

The solution implemented in #24 hacks around this so that the tfvm installer downloads the `amd64_darwin` build and uses that, which causes the `amd64_darwin` builds to be downloaded from the Terraform releases site. It also means that we can’t use the `arm64_darwin` builds that are now available (since 1.0.2; 1.0.1 and earlier _only_ have `amd64_darwin` builds).

As far as I can tell, native `arm64_darwin` binaries can launch `amd64_darwin` binaries, but not the other way around. The changes required to the download algorithm would be (only on an `arm64_darwin` build):

- if on `arm64_darwin`, then see if there’s an `arm64_darwin` build on the Terraform release.
  - if yes, download and use that
  - if no, download the `amd64_darwin` build instead and use that

What I’ve done now _works_, but is suboptimal. For people like me who have installed and used the `amd64_darwin` build, we’d need to remove the tfvm cache so that downloaded versions could be replaced with native versions if possible, but it would give us a much better result overall.

**Comment by cbuschka** [comment]
Hey @halostatue, thanks for your patience. Had a system migration on weeked, was like walking to Mordor :smile: 

Have prototyped platform support and fallback to darwin/amd64. Would you mind to test it on your darwin/arm64 mac. I just have run out of arm macs :)

If you need a prebuilt binary, drop me a note, I can prepare a prerelease.

**Comment by halostatue** [comment]
I’ll be able to test this in a couple of hours.

**Comment by halostatue** [comment]
First problem: the `Makefile` produces no `arm64` build.

```
dist/tfvm-darwin_amd64:      Mach-O 64-bit executable x86_64
dist/tfvm-linux_386:         ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, Go BuildID=PYmiblQKu3OaPMZMn9i1/_Mc6CJso1BoXZ07VHBvk/6HoTx9QXCVhie9-K1bsb/3bGkPMyJNFhCkMM1xdrB, not stripped
dist/tfvm-linux_amd64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=C7K7b5MCKac7RtaXbESS/5rFkWna5vTxzdyPB3m6f/WeuUQGpTn4SdtclxxgnE/ANcGUHFZ1qqHo-Qxjxz-, not stripped
dist/tfvm-windows_386.exe:   PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
dist/tfvm-windows_amd64.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by halostatue** [comment]
This should be fixed with this:

```diff
diff --git i/Makefile w/Makefile
index 5e3b4ea18900..b9dbfa60662b 100644
--- i/Makefile
+++ w/Makefile
@@ -73,10 +73,17 @@ build_windows:	build
 	$(call build_binary,windows,amd64,.exe)
 	$(call build_binary,windows,386,.exe)
 
-build_macosx:	build
+build_macosx:	build_macosx_amd64 build_macosx_arm64
 	@echo "### Building Mac OS X variants..."
 	$(call build_binary,darwin,amd64,)
 
+build_macosx_amd64:	build
+	@echo "### Building Mac OS X variants..."
+	$(call build_binary,darwin,amd64,)
+
+build_macosx_arm64:	build
+	$(call build_binary,darwin,arm64,)
+
 test:	init
 	@echo "### Running unit tests..."
 	go test -cover -race -coverprofile=coverage.txt -covermode=atomic ./internal/... ./cmd/...
```

**Comment by halostatue** [comment]
```
dist/tfvm-darwin_amd64:      Mach-O 64-bit executable x86_64
dist/tfvm-darwin_arm64:      Mach-O 64-bit executable arm64
dist/tfvm-linux_386:         ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, Go BuildID=eE_t28_q5xJ_z7bSyo6Q/_Mc6CJso1BoXZ07VHBvk/6HoTx9QXCVhie9-K1bsb/EIT4vQQHYG0bp2UM_0Vd, not stripped
dist/tfvm-linux_amd64:       ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=xxOlpZUd-JdsidOE4TTL/5rFkWna5vTxzdyPB3m6f/WeuUQGpTn4SdtclxxgnE/r6DJ3mC8VzuL1iBuHwe7, not stripped
dist/tfvm-windows_386.exe:   PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
dist/tfvm-windows_amd64.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by halostatue** [comment]
Zeroth problem: the Makefile required GNU make v4+ and Go 1.16. I needed to install a new make (the default on macOS is GNU make 3.8-something) and a go version manager to get to Go 1.16 (I was on Go 1.17 as I am not really a go developer so much as a go program _user_).

**Comment by halostatue** [comment]
I have one repo that is on 0.14.4 and one that is on 1.0.2. Thus, I expect a amd64 build (0.14.4) to be installed and an arm64 build (1.0.2) to be installed, since that’s what is available.

1.0.2 happens, but 0.14.4 does not. Here’s the content of `~/.cache/tfvm` after running `tfvm install` in each (they both have `.terraform-version` files):

```
v1
v1/state.json
v1/installed
v1/installed/1.0.2
v1/installed/1.0.2/darwin_arm64
v1/installed/1.0.2/darwin_arm64/terraform
```

The 0.14.4 fails with the following message:

```
❯ tfvm install
Downloading terraform 0.14.4...
Installing terraform 0.14.4...
Unzipping failed: zip: not a valid zip file
```

My _guess_ (I haven’t looked at the code) is that you’re downloading `0.14.4` for arm64 and expecting a 404 in the event of a missing file and that’s not happening for some reason. The 404 should then cause a fallback to `amd64`, but that’s not happening.

**Comment by cbuschka** [comment]
Hey @halostatue , thanks for trying out. And I am very sorry for the inconveniences caused by asking you to build it on your own. I will create a prerelease, so you can download it and try it out.

I am not sure, which version you finally have run. I cannot find commit 5e3b4ea18900 in the [conni_25_add_darwin_arm64_with_tf_darwin_amd64_fallback](https://github.com/cbuschka/tfvm/tree/conni_25_add_darwin_arm64_with_tf_darwin_amd64_fallback) branch. It could be that it has been lost because I have rebased the branch in the meantime.

Could you save your state.json file and try out the darwin binaries from Release [v0.19.0.rc1](https://github.com/cbuschka/tfvm/releases/tag/v0.19.0.rc1)? If it fails again, could you send me your state.json before and after execution? Thank you for your patience.

**Comment by cbuschka** [comment]
@halostatue  When you test it, can you send me your output too. I test it this way with os/arch override:

[conni@dudu tfvm]$ TFVM_TERRAFORM_OS=darwin TFVM_TERRAFORM_ARCH=arm64 ~/Downloads/tfvm-linux_amd64 install 0.14.4
Downloading terraform 0.14.4 for darwin/amd64...
Installing terraform 0.14.4 for darwin/amd64...
Terraform 0.14.4 for darwin/amd64 installed.
[conni@dudu tfvm]$ TFVM_TERRAFORM_OS=darwin TFVM_TERRAFORM_ARCH=arm64 ~/Downloads/tfvm-linux_amd64 install 1.0.2
Downloading terraform 1.0.2 for darwin/arm64...
Installing terraform 1.0.2 for darwin/arm64...
Terraform 1.0.2 for darwin/arm64 installed.

How does it look on your system?

**Comment by halostatue** [comment]
OMG. I was testing on `main`. I’m sorry.

When building correctly, `tfvm version` reports `v0.18.0-64-g29a43ef182aa`.

When I am using the branch you told me to use in the first place, I get _much_ better results.

```
~/.cache/tfvm/v1/state.json: JSON data
~/.cache/tfvm/v1/installed/0.14.4/darwin_amd64/terraform: Mach-O 64-bit executable x86_64
~/.cache/tfvm/v1/installed/1.0.2/darwin_arm64/terraform: Mach-O 64-bit executable arm64
```

It works perfectly.

**Comment by cbuschka** [comment]
Hey @halostatue thank you for the enhancement proposal, for your time and the great support.

I have created release v0.19.0 with **thanks to your contribution** first class darwin/arm64 support.

Feel free to raise an issue if needed. Would be very happy to hear from you.
