### ISSUE TITLE
Default cache dir on macOS

### ISSUE THREAD

**Issue by cbuschka** [cbuschka/tfvm#29]
* [ ] This is a bug report
* [x] This is a feature request

### Expected behavior

When ~/.tfvm does not exist, the default cache dir on macOS should be ~/Library/Caches/tfvm/. As suggested by @halostatue in https://github.com/cbuschka/tfvm/pull/28

### Actual behavior

When ~/.tfvm does not exist, tfvm chooses .cache/tfvm as XDG suggests.

### Steps to reproduce the behavior

Remove ~/.tfvm and run tfvm list

**Comment by halostatue** [comment]
I think that this is the correct change, but I would suggest a slightly smoother migration, as I have installations in `~/.cache/tfvm`. Namely, if on macOS, it seems to me that we should check for the existence of `TFVM_DIR`, then `XDG_CACHE_DIR`, _then_ if that isn’t present, use the correct `~/Library/Caches/tfvm` location. There’s not a _lot_ of migration I would have (only two versions installed), but for other macOS users this will require redownloading all the versions.

If you wish to keep the code simpler, updating the README to suggest setting `TFVM_DIR=~/.cache/tfvm` on upgrade to the next version would be good.

Thanks again for such a great tool.

**Comment by halostatue** [comment]
👍

**Comment by cbuschka** [comment]
Yes, sounds reasonable.

Setting TFVM_DIR could be an option. But I would prefer not forcing people into setting env vars. So the suggested solution - use ~/.cache/tfvm dir if it already exists on macOS too - is a good solution in my opinion.

No, code complexity should not be an issue for now. Also I become better at unit testing and mocking in Go ;)

Could you review a9eae97?

**Comment by cbuschka** [comment]
Ah, you already have :smile:

**Comment by cbuschka** [comment]
Provided with https://github.com/cbuschka/tfvm/releases/tag/v0.22.0
