### ISSUE TITLE
Using a GNU awk extension for version selection

### ISSUE THREAD

**Issue by halostatue** [cbuschka/tfvm#33]
Hi. I ported the version selection tooling used in `install.sh` to [mattn/vim-lsp-settings](https://github.com/mattn/vim-lsp-settings) and bug mattn/vim-lsp-settings#540 was reported on a version of macOS which did not have GNU awk installed. The fix was suggested to be mattn/vim-lsp-settings#541.

For maximum cross-platform compatibility, I would suggest that the fix for the above issue be applied here.

**Comment by cbuschka** [comment]
Hey @halostatue thank you for the suggestion. The nice thing I love about software development is: there is always a way to make it better :D

Could you please review the [https://github.com/cbuschka/tfvm/commit/94271de8323ed0a571a2dbc0f4ffaad40a39b686](change) ?

All the best (and peace)
Conni

**Comment by halostatue** [comment]
This seems to work:

```sh
$ basename $(curl -Ls -o /dev/null -w %\{url_effective\} https://github.com/cbuschka/tfvm/releases/latest)
v0.22.0
```

**Comment by halostatue** [comment]
If you need just the `0.22.0`, you will also want to add  `| cut -c2-`.

**Comment by cbuschka** [comment]
the previous implementation returned the leading v too:
[conni@herbie tfvm]$ curl --silent "https://api.github.com/repos/cbuschka/tfvm/releases/latest" | awk 'match($0, /"tag_name": "(.+)"/, a) { print a[1] }'
v0.22.0

@halostatue Thanks for reviewing! Thanks for suggesting the improvement.
