### ISSUE TITLE
Installation as root does not install to `/usr/local/bin`

### ISSUE THREAD

**Issue by TylerHendrickson** [cbuschka/tfvm#46]
* [x] This is a bug report
* [ ] This is a feature request

### Expected behavior

According to the readme, installing as root should install to `/usr/local/bin`:
> ## Installation
>
> ### as root in /usr/local/bin
>
> ```
> curl -sL https://raw.githubusercontent.com/cbuschka/tfvm/main/install.sh -o - | sudo bash
> ```

### Actual behavior

Running the install as root results in `tfvm` installed to `${HOME}/bin` (e.g. `/root/bin`).

### Steps to reproduce the behavior

Follow the directions in the readme:
```cli
$ curl -sL https://raw.githubusercontent.com/cbuschka/tfvm/main/install.sh -o - | sudo bash
Will install tfvm as /root/bin/tfvm and /root/bin/terraform.
```

To verify:
```cli
$ sudo find /usr/local/bin -name tfvm
$ sudo find /root/bin -name tfvm
/root/bin/tfvm
```

**Output of `tfvm info`:**

```
Tfvm version is v0.24.0.
Built from commitish 6f92877, on 2022-11-22 20:08:20+01:00 for linux/amd64.
OS is linux, arch is amd64.
Cache dir is /root/.cache/tfvm.
Workspace dir is /.
Config loaded from [defaults].
```
**Output of `TF_LOG=trace tfvm <your command>`:**

N/A

**Additional environment details**

Verified behavior running in `ubuntu:latest` and `debian:bookworm` docker images.

**Comment by TylerHendrickson** [comment]
Just to add: I believe I located the source of the issue in [install.sh#L6-L14](https://github.com/cbuschka/tfvm/blob/main/install.sh#L6-L14):
```sh
if [ "x" = "x${TARGET_DIR}" ]; then
  TARGET_DIR=/usr/local/bin/
  if [ "${UID}" != "0" ] && [ -d "${HOME}/.local/bin" ] && [ ! -f "${HOME}/bin/tfvm" ]; then
    TARGET_DIR=${HOME}/.local/bin
  else
    TARGET_DIR=${HOME}/bin
  fi
fi
mkdir -p ${TARGET_DIR}
```

Modifying that section of the install script like this seems to resolve the issue:
```sh
if [ "x" = "x${TARGET_DIR}" ]; then
  if [ "${UID}" = "0" ]; then
    TARGET_DIR=/usr/local/bin/
  elif [ -d "${HOME}/.local/bin" ] && [ ! -f "${HOME}/bin/tfvm" ]; then
    TARGET_DIR=${HOME}/.local/bin
  else
    TARGET_DIR=${HOME}/bin
  fi
fi
mkdir -p ${TARGET_DIR}
```

**Comment by cbuschka** [comment]
Hey @TylerHendrickson , thanks for submitting the bug request. Yes, you are right. I have chosen the pure sequential fix. Thanks for contributing. Feel free to raise issues and PR. Hope you enjoy working with tfvm. All the Best, Conni.
